// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Services.Doctors.Persistence.CompiledEntities;
using Services.Doctors.Persistence.Context;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
