// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Services.Doctors.Persistence.CompiledEntities
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("42b6bf30-61a8-406b-8dd0-6d633c4027b9"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var doctor = DoctorEntityType.Create(this);

            DoctorEntityType.CreateAnnotations(doctor);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.0");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
