name: CI Pipeline

on:
  pull_request:
    branches:
      - 'sprint*'
      - development

  push:
    branches:
      - main
env:
  SOLUTION_DIR: ./src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set up .NET Core 
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - name: Give access to private nugets (dependencies)
        run: dotnet nuget add source --username ocb-dev-04 --password ${{ secrets.NUGET_AUTH_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ocb-dev-04/index.json"
    
      # - name: Restore NuGet Packages
      #   run: dotnet restore ${{ env.SOLUTION_DIR }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_DIR }} --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_DIR }} --no-restore --verbosity normal
